# Generated by Django 2.0 on 2018-12-11 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Chronos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=64)),
                ('numero', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='timetracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_seance', models.IntegerField()),
                ('id_week', models.IntegerField()),
                ('id_year', models.IntegerField()),
                ('fk_id_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chronos.Project')),
                ('fk_id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chronos.User')),
            ],
        ),
        migrations.AddField(
            model_name='affectation',
            name='id_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chronos.Project'),
        ),
        migrations.AddField(
            model_name='affectation',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Chronos.User'),
        ),
    ]
