# Generated by Django 2.0 on 2018-12-15 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Chronos', '0002_auto_20181211_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(related_name='projects', to='Chronos.User'),
        ),
        migrations.AlterField(
            model_name='affectation',
            name='id_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affected_projects', to='Chronos.Project'),
        ),
    ]
