# Generated by Django 2.0 on 2018-12-15 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Chronos', '0003_auto_20181215_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affectation',
            name='id_project',
        ),
        migrations.RemoveField(
            model_name='affectation',
            name='id_user',
        ),
        migrations.AlterField(
            model_name='timetracking',
            name='fk_id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetracked_projects', to='Chronos.User'),
        ),
        migrations.DeleteModel(
            name='Affectation',
        ),
    ]
